// TeamSlice.js
import { createSlice } from '@reduxjs/toolkit';
import { v4 as uuidv4 } from 'uuid';

export const TeamDetails = {
  secondYear: [
    {
      id: uuidv4(),
      name: "Bhavya Ailani",
      year: "2nd Year",
      role: "Co-Coorinator(Management)",
      linkedIn: "https://www.linkedin.com/in/bhavya-ailani-0540a223b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "bhavyaailani13@gmail.com",
      instagram: "https://www.instagram.com/bhavyaailani_/profilecard/?igsh=MXM1aGdtcXdlOGhmaA==",
      profileImage: "",
    },
    
    {
      id: uuidv4(),
      name: "Nikhil Solanki",
      year: "2nd Year",
      role: "Event Manager",
      linkedIn: "https://www.linkedin.com/in/nikhil-solanki-a7a",
      email: "nikhilsolanki2306@gmail.com",
      instagram: "https://www.instagram.com/_n_i_k_k_23/profilec",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Piyush Yadav",
      year: "2nd Year",
      role: "Event Manager",
      linkedIn: "https://linkedin.com/in/piyushyadav2307",
      email: "yadavpiyush68144@gmail.com",
      instagram: "https://www.instagram.com/piyush_yadav2307",
      profileImage: "",
    },
    // {
    //   id: uuidv4(),
    //   name: "",
    //   year: "2nd Year",
    //   role: "Event Manager",
    //   linkedIn: "",
    //   email: "",
    //   instagram: "",
    //   profileImage: "",
    // },
    {
      id: uuidv4(),
      name: "Rohan Kumar",
      year: "2nd Year",
      role: "Event Manager",
      linkedIn: "https://wwww.linkedin.com/in/rohan-kumar-80862a301ww.linkedin.com/in/",
      email: "rohankk370@gmail.com",
      instagram: "https://www.instagram.com/rohan.kr_3",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Akshat Arora",
      year: "2nd Year",
      role: "Event Manager",
      linkedIn: "https://www.linkedin.com/in/akshat-arora-6a21a4290?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "akshatarora241@gmail.com",
      instagram: "https://www.instagram.com/",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Umang Rathod",
      year: "2nd Year",
      role: "Event Manager",
      linkedIn: "https://www.linkedin.com/in/umang-rathod-8b16062b6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "umangrathod7492@gmail.com",
      instagram: "https://www.instagram.com/umannngggg?igsh=a3NzZnQ5eHAwN2Vi",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Ankit Singh",
      year: "2nd Year",
      role: "Event Manager",
      linkedIn: "https://www.linkedin.com/in/ankit-singh-78152b1b5/",
      email: "ankit132004singh@gmail.com",
      instagram: "https://www.instagram.com/ankit_shekhawat1326",
      profileImage: "",
    },



    {
      id: uuidv4(),
      name: "Anuj Gour",
      year: "2nd Year",
      role: "FinTech",
      linkedIn: "https://www.linkedin.com/in/anuj-gour-13198a28a",
      email: "anujgour0124@gmail.com",
      instagram: "https://www.instagram.com/anujgour_27/profilec",
      profileImage: "https://res.cloudinary.com/dju84uvhd/image/upload/v1737660122/pixelcut-export_-_Anuj_Gour_ovbibc.png",
    },
    {
      id: uuidv4(),
      name: "Prakhar Dubey",
      year: "2nd Year",
      role: "FinTech",
      linkedIn: "https://www.linkedin.com/in/prakhardubey110",
      email: "prakhardubey110@gmail.com",
      instagram: "https://www.instagram.com/prakhar_110",
      profileImage: "",
    },
    //fin
    {
      id: uuidv4(),
      name: "Prakhar Dubey",
      year: "2nd Year",
      role: "FinTech",
      linkedIn: "https://www.linkedin.com/in/prakhardubey110",
      email: "prakhardubey110@gmail.com",
      instagram: "https://www.instagram.com/prakhar_110",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Prakhar Dubey",
      year: "2nd Year",
      role: "FinTech",
      linkedIn: "https://www.linkedin.com/in/prakhardubey110",
      email: "prakhardubey110@gmail.com",
      instagram: "https://www.instagram.com/prakhar_110",
      profileImage: "",
    },


// spon
    {
      id: uuidv4(),
      name: "Anupam Kumar Tiwari",
      year: "2nd Year",
      role: "Sponsorship Executive",
      linkedIn: "https://www.linkedin.com/in/anupam-kumar-tiwari",
      email: "apriyam2005@gmail.com",
      instagram: "https://www.instagram.com/anupam_nitb/profilec",
      profileImage: "https://res.cloudinary.com/dju84uvhd/image/upload/v1737660122/Photoroom-20241026_151614_-_Anupam_Kumar_Tiwari_rptord.png",
    },
    {
      id: uuidv4(),
      name: "Anchal Verma",
      year: "2nd Year",
      role: "Sponsorship Executive",
      linkedIn: "https://www.linkedin.com/in/anchal-verma-4b5716341?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "verma20.09.aashi@gmail.com",
      instagram: "https://www.instagram.com/__aashi__20?igsh=MWhwaXp3YzAzZDRvaQ==",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Ayush Meena",
      year: "2nd Year",
      role: "Sponsorship Executive",
      linkedIn: "https://www.linkedin.com/in/ayush-meena-953557285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "meenaayushno1@gmail.com",
      instagram: "https://www.instagram.com/ayushmeena_7/profilecard/?igsh=NGdrc2E1Mms2bzRh",
      profileImage: "",
    },


    {
      id: uuidv4(),
      name: "Ram Kumar",
      year: "2nd Year",
      role: "Web Developer",
      linkedIn: "https://www.linkedin.com/in/ram-kumar999",
      email: "ramkumar18092005@gmail.com",
      instagram: "https://www.instagram.com/Ram_kumar_9525",
      profileImage: "", 
    },
    {
      id: uuidv4(),
      name: "Harish Kushwaha",
      year: "2nd Year",
      role: "Web Developer",
      linkedIn: "https://www.linkedin.com/in/harish-kushwaha-3895a428b/",
      email: "h.kush2005@gmail.com",
      instagram: "https://www.instagram.com/harish.k_ush_05/",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Vaibhav Mandwar",
      year: "2nd Year",
      role: "Photographer",
      linkedIn: "https://www.linkedin.com/in/Vaibhav Mandwar",
      email: "vaibhavmb97@gmail.com",
      instagram: "https://www.instagram.com/waybhav_07",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Ujjwal Kumar",
      year: "2nd Year",
      role: "Photographer",
      linkedIn: "https://www.linkedin.com/in/ujjwal-kumar-8547bb2b5/",
      email: "ujjwalkr.com@gmail.com",
      instagram: "https://www.instagram.com/uk.4289?igsh=bGR4aWN0b3V5dTkx",
      profileImage: "",
    },
    
  ],
  thirdYear: [
    {
      id: uuidv4(),
      name: "Shriyansh Chourasiya",
      year: "3rd Year",
      role: "Co-coordinator (Admin)",
      linkedIn: "https://www.linkedin.com/in/shriyansh-chourasiya",
      email: "shriyanshchourasiya96@gmail.com",
      instagram: "https://www.instagram.com/ll_mr.unpredictable_",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "KARAN CHOUDHARY",
      year: "3rd Year",
      role: "Co-Coordinator(Management)",
      linkedIn: "https://www.linkedin.com/in/karan-choudhary-8b",
      email: "krnchdryoo7@gmail.com",
      instagram: "https://www.instagram.com/aisenh_037/",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Rishabh Patel",
      year: "3rd Year",
      role: "Operational Head",
      linkedIn: "https://www.linkedin.com/in/rishabh-patel-27bb",
      email: "rishabh558patel@gmail.com",
      instagram: "https://www.instagram.com/risheclipse",
      profileImage: "https://res.cloudinary.com/dju84uvhd/image/upload/v1737660479/IMG_20241122_190630_263_-_Rishabh_patel_zzvrnm.webp",
    },
    {
      id: uuidv4(),
      name: "Ayush Gautam",
      year: "3rd Year",
      role: "Cordinator",
      linkedIn: "https://www.linkedin.com/in/ayush-gautam-15731",
      email: "ayushgautam5v@gmail.com",
      instagram: "https://www.instagram.com/",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Arman Pal",
      year: "3rd Year",
      role: "Web Development Head",
      linkedIn: "https://www.linkedin.com/in/",
      email: "armanpal272005@gmail.com",
      instagram: "https://www.instagram.com/",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Dileep Bhargav",
      year: "3rd Year",
      role: "Fintech Head",
      linkedIn: "https://www.linkedin.com/in/dileep-bhargav89/",
      email: "dileepbhargav722@gmail.com",
      instagram: "https://www.instagram.com/dileepbz._/profilecard/?igsh=Ync2eDB4bXBxeTJ2",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Varun Jain",
      year: "3rd Year",
      role: "Fintech Head",
      linkedIn: "https://www.linkedin.com/in/varun-jain08",
      email: "varunvj8804@gmail.com",
      instagram: "https://www.instagram.com/varun.8_8",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Shreyas Raut",
      year: "3rd Year",
      role: "Promotion and outreach head",
      linkedIn: "https://www.linkedin.com/in/shreyas-raut-643a9a256?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "shreyas.raut04@gmail.com",
      instagram: "https://www.instagram.com/shreyasraut99?igsh=MWN4N3NqdWY3ZXdkNA==",
      profileImage: "",
    },
    {
      id: uuidv4(),
      name: "Vedant Kumar Namdev",
      year: "3rd Year",
      role: "Content and Designing Head",
      linkedIn: "https://www.linkedin.com/in/vedant-kumar-namdev-31228a257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "",
      instagram: "https://www.instagram.com/vedantknamdev?utm_source=qr&igsh=MWNoNGtoMGwyN3c2Zg==",
      profileImage: "",
    },
  ],
};

const teamSlice = createSlice({
  name: 'team',
  initialState: TeamDetails,
  reducers: {},
});

export default teamSlice.reducer;
